osx_image: xcode11.3
language: swift

xcode_project: /RImage/RImage.xcodeproj # path to your xcodeproj folder
xcode_scheme: RImageTests
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone XR